-- Schema base de la app (Registro de ingreso).
--
-- Estas tablas se crearon a mano desde el SQL Editor de Supabase antes de que
-- el proyecto usara migraciones, y este archivo quedó vacío. Se completó en
-- septiembre de 2026 a partir de `supabase db dump` de producción, para que
-- `supabase db reset` pueda reconstruir la base desde cero.
--
-- Refleja el estado previo a las migraciones siguientes, que lo modifican:
--   - 20260829000000_organizaciones: agrega asistencias.organizacion_id y el
--     scoping por organización (pibes ya tenía la columna).
--   - 20260927000000_cerrar_acceso_publico: saca las políticas "public ..."
--     de abajo, que dejaban todo abierto a anon.
--
-- En producción esta versión ya figura como aplicada: modificar este archivo
-- NO la vuelve a ejecutar allá.

create extension if not exists unaccent with schema extensions;

-- ─────────────────────────────────────────────────────────
-- Privilegios por defecto
--
-- En producción, las tablas y funciones nuevas de public NO reciben SELECT /
-- INSERT / EXECUTE automáticos para anon, authenticated ni service_role: cada
-- migración tiene que otorgar explícitamente lo que necesita (por eso los
-- "permission denied (42501)" que aparecen en DATABASE.md). El stack local de
-- Supabase trae el default viejo (GRANT ALL), que tapaba ese error; esto lo
-- iguala a producción.
-- ─────────────────────────────────────────────────────────

alter default privileges for role postgres in schema public
  revoke all on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant references, trigger, truncate, maintain on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke all on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke all on functions from anon, authenticated, service_role;

-- ─────────────────────────────────────────────────────────
-- Organizaciones y catálogos
-- ─────────────────────────────────────────────────────────

create table if not exists public.organizaciones (
  created_at timestamptz not null default now(),
  nombre varchar not null default '' unique,
  id uuid primary key default gen_random_uuid()
);
comment on table public.organizaciones is
  'Tabla de organizaciones. Cada organización corresponda a cada espacio (por ej: oratorio de garay, escuadra 3, etc)';

create table if not exists public.niveles_grados_pibes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nivel varchar not null unique
);
comment on table public.niveles_grados_pibes is
  'Tabla de los niveles de los grados de los pibes. Inicial / Primario / Secundario';

create table if not exists public.grados_pibes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nivel varchar not null references public.niveles_grados_pibes(nivel) on update cascade on delete restrict,
  grado smallint not null
);
comment on table public.grados_pibes is
  'Tabla de los grados de los pibes. Por ej: 1° (Nivel: Primario), 2° (nivel: Primario), ...., 1° año (nivel: Secundario), etc';

create table if not exists public.edades (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nombre varchar not null,
  organizacion_id uuid not null references public.organizaciones(id) on delete cascade
);
comment on table public.edades is
  'Tabla de edades. En cada espacio se organizan por edades/grupos/etapas/etc';

-- ─────────────────────────────────────────────────────────
-- Pibes y asistencias
-- ─────────────────────────────────────────────────────────

create table if not exists public.pibes (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  nombre varchar not null,
  apellido varchar not null,
  grado_id bigint not null references public.grados_pibes(id) on update cascade on delete restrict,
  entrego_ficha boolean not null,
  telefono_emergencia bigint,
  edad_id bigint not null references public.edades(id) on update cascade on delete restrict,
  observaciones text,
  -- Pasa a not null en 20260829000000_organizaciones.
  organizacion_id uuid references public.organizaciones(id) on delete restrict
);
comment on table public.pibes is 'Tabla de los pibes';

create index if not exists idx_pibes_nombre on public.pibes (nombre);
create index if not exists idx_pibes_apellido on public.pibes (apellido);

-- organizacion_id se agrega en 20260829000000_organizaciones.
create table if not exists public.asistencias (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  fecha timestamptz not null,
  pibe_id uuid not null default gen_random_uuid()
    references public.pibes(id) on update cascade on delete restrict
);
comment on table public.asistencias is 'Tabla de asistencias de los pibes';

create index if not exists idx_asistencias_pibe_id on public.asistencias (pibe_id);

-- ─────────────────────────────────────────────────────────
-- Búsqueda de pibes (RPC usada por GET /api/students/search)
--
-- Coincidencia parcial, sin distinguir mayúsculas ni tildes, en nombre o
-- apellido. SECURITY INVOKER: respeta la RLS de pibes. El filtro por
-- organización lo agrega el backend encadenando .eq("organizacion_id", ...).
-- ─────────────────────────────────────────────────────────

create or replace function public.buscar_pibes(termino text)
returns setof public.pibes
language sql
stable
set search_path = ''
as $$
  select p.*
  from public.pibes as p
  where
    extensions.unaccent(lower(p.nombre))
      ilike '%' || extensions.unaccent(lower(termino)) || '%'
    or
    extensions.unaccent(lower(p.apellido))
      ilike '%' || extensions.unaccent(lower(termino)) || '%';
$$;

-- ─────────────────────────────────────────────────────────
-- RLS automática en tablas nuevas de public
--
-- Así está configurado el proyecto de producción: toda tabla nueva en public
-- nace con RLS habilitada. Crear un event trigger requiere superusuario; si
-- el rol que corre la migración no lo es, se deja sólo la función y se avisa.
-- ─────────────────────────────────────────────────────────

create or replace function public.rls_auto_enable()
returns event_trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;

do $$
begin
  if not exists (select 1 from pg_event_trigger where evtname = 'ensure_rls') then
    create event trigger ensure_rls on ddl_command_end
      execute function public.rls_auto_enable();
  end if;
exception when insufficient_privilege then
  raise notice 'Sin permisos para crear el event trigger ensure_rls: se omite.';
end $$;

-- ─────────────────────────────────────────────────────────
-- RLS y permisos originales
--
-- ⚠️ Estas políticas son el estado original (abierto a anon) y se reproducen
-- tal cual por fidelidad histórica. 20260927000000_cerrar_acceso_publico las
-- elimina. NO copiar este patrón.
-- ─────────────────────────────────────────────────────────

alter table public.organizaciones enable row level security;
alter table public.niveles_grados_pibes enable row level security;
alter table public.grados_pibes enable row level security;
alter table public.edades enable row level security;
alter table public.pibes enable row level security;
alter table public.asistencias enable row level security;

drop policy if exists "public read organizaciones" on public.organizaciones;
create policy "public read organizaciones" on public.organizaciones for select using (true);
drop policy if exists "public read niveles" on public.niveles_grados_pibes;
create policy "public read niveles" on public.niveles_grados_pibes for select using (true);
drop policy if exists "public read grados" on public.grados_pibes;
create policy "public read grados" on public.grados_pibes for select using (true);
drop policy if exists "public read edades" on public.edades;
create policy "public read edades" on public.edades for select using (true);
drop policy if exists "public read pibes" on public.pibes;
create policy "public read pibes" on public.pibes for select using (true);
drop policy if exists "public insert pibes" on public.pibes;
create policy "public insert pibes" on public.pibes for insert with check (true);
drop policy if exists "public update pibes" on public.pibes;
create policy "public update pibes" on public.pibes for update using (true);
drop policy if exists "public read asistencias" on public.asistencias;
create policy "public read asistencias" on public.asistencias for select using (true);
drop policy if exists "public insert asistencias" on public.asistencias;
create policy "public insert asistencias" on public.asistencias for insert with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant all on public.pibes, public.asistencias to anon, authenticated, service_role;
grant select on public.organizaciones, public.grados_pibes, public.edades
  to anon, authenticated, service_role;
grant select on public.niveles_grados_pibes to anon;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
